#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON_BIN="${PREDIFY_PYTHON_BIN:-/home/lin/anaconda3/envs/predifyproject/bin/python}"
MODE="${1:-formal}"
CHECKPOINT="${PREDIFY_SEMANTIC_TEMPORAL_ERROR_CHECKPOINT:-/home/lin/experiments/kitti_step_semantic_temporal_error_correction_10epoch_ffb1a74/best_semantic_temporal_error_correction.pt}"
REVISION="$(git -C "$REPO_ROOT" rev-parse HEAD)"
SHORT_REVISION="${REVISION:0:7}"

if [[ "$MODE" == "smoke" ]]; then
    OUTPUT_DIR="${PREDIFY_CITYSCAPES_C_OUTPUT_DIR:-/tmp/kitti_step_cityscapes_c_smoke_${SHORT_REVISION}}"
    CORRUPTIONS="${PREDIFY_CITYSCAPES_C_CORRUPTIONS:-gaussian_noise}"
    SEVERITIES="${PREDIFY_CITYSCAPES_C_SEVERITIES:-1}"
    MAX_SEQUENCES="${PREDIFY_CITYSCAPES_C_MAX_SEQUENCES:-1}"
    NUM_WORKERS="${PREDIFY_CITYSCAPES_C_NUM_WORKERS:-4}"
    CACHED_CORRUPTIONS="${PREDIFY_CITYSCAPES_C_CACHED_CORRUPTIONS:-}"
elif [[ "$MODE" == "formal" ]]; then
    OUTPUT_DIR="${PREDIFY_CITYSCAPES_C_OUTPUT_DIR:-$REPO_ROOT/results/kitti_step_cityscapes_c_${SHORT_REVISION}}"
    CORRUPTIONS="${PREDIFY_CITYSCAPES_C_CORRUPTIONS:-}"
    SEVERITIES="${PREDIFY_CITYSCAPES_C_SEVERITIES:-}"
    MAX_SEQUENCES="${PREDIFY_CITYSCAPES_C_MAX_SEQUENCES:-0}"
    NUM_WORKERS="${PREDIFY_CITYSCAPES_C_NUM_WORKERS:-8}"
    CACHED_CORRUPTIONS="${PREDIFY_CITYSCAPES_C_CACHED_CORRUPTIONS:-glass_blur}"
else
    echo "Usage: $0 [smoke|formal]" >&2
    exit 2
fi

"$PYTHON_BIN" -c "import imagecorruptions" >/dev/null

PREDIFY_GIT_REVISION="$REVISION" \
PREDIFY_KITTI_STEP_ROOT="${PREDIFY_KITTI_STEP_ROOT:-/home/lin/predify/kitti_step}" \
PREDIFY_SEMANTIC_TEMPORAL_ERROR_CHECKPOINT="$CHECKPOINT" \
PREDIFY_CITYSCAPES_C_OUTPUT_DIR="$OUTPUT_DIR" \
PREDIFY_CITYSCAPES_C_CORRUPTIONS="$CORRUPTIONS" \
PREDIFY_CITYSCAPES_C_SEVERITIES="$SEVERITIES" \
PREDIFY_CITYSCAPES_C_MAX_SEQUENCES="$MAX_SEQUENCES" \
PREDIFY_CITYSCAPES_C_NUM_WORKERS="$NUM_WORKERS" \
PREDIFY_CITYSCAPES_C_PREFETCH_FACTOR="${PREDIFY_CITYSCAPES_C_PREFETCH_FACTOR:-4}" \
PREDIFY_CITYSCAPES_C_CACHE_ROOT="${PREDIFY_CITYSCAPES_C_CACHE_ROOT:-/home/lin/predify/kitti_step_cityscapes_c_cache}" \
PREDIFY_CITYSCAPES_C_CACHED_CORRUPTIONS="$CACHED_CORRUPTIONS" \
PREDIFY_SEED="${PREDIFY_SEED:-0}" \
PYTHONPATH="$REPO_ROOT:${PYTHONPATH:-}" \
"$PYTHON_BIN" -u -m predify2021.mce_scores.evaluate_kitti_step_cityscapes_c
